disorderedmaterials/GudPy

.azure-pipelines/continuous.yml
.azure-pipelines/templates/build.yml
.azure-pipelines/templates/test.yml
gudpy.spec
gudrun_classes/gudrun_file.py
gudrun_classes/sample_background.py
tests/test_gudpy_io.py

- Added a range of tests for attempting to load Gudrun files with missing classes/atrributes.
- Added acquisition of Gudrun binaries to the test and build pipelines.
- Gudrun binaries are packed with executable built by pyinstaller.

CI with Gudrun

---

gudrun_classes/gud_file.py
gudrun_classes/gudrun_file.py
tests/test_gud_file.py
tests/test_gudpy_io.py

A wide range of tests have been added for testing the input and output functionalities of GudPy and Gudrun. This includes parsing files (.gud and input files) and writing them out again as well as running gudrun_dcs and evaluating its outputs in terms of diagnostic files, and the output produced by stdout.

Comprehensive testing for GudPy and Gudrun I/O

---

.gitignore
gudrun_classes/__init__.py
gudrun_classes/beam.py
gudrun_classes/composition.py
gudrun_classes/container.py
gudrun_classes/data_files.py
gudrun_classes/element.py
gudrun_classes/gud_file.py
gudrun_classes/gudrun_file.py
gudrun_classes/instrument.py
gudrun_classes/normalisation.py
gudrun_classes/sample.py
gudrun_classes/sample_background.py
gui/gudpy.py
scripts/utils.py
tests/TestData/NIMROD-water/gudpy_water.txt
tests/test_gud_file.py
tests/test_gudpy_io.py
tests/test_gudrun_classes.py
tests/test_utils.py
widgets/gudrun_file_text_area.py
widgets/main_widget.py
widgets/main_window.py
widgets/sidebar.py
widgets/text_area.py

Applied autopep8 to format code to conform to PEP8 standards. Then consulted flake8 outputs to ensure that the entire codebase conforms to PEP8 (see https://www.python.org/dev/peps/pep-0008/). Closes issue #16.

Format code.

---

gudrun_classes/gudrun_file.py
gudrun_classes/sample.py
gudrun_classes/tweak_factor_iterator.py
tests/test_gud_file.py
tests/test_gudpy_io.py
tests/test_gudpy_workflows.py

Added functionality for iterating gudrun_dcs by tweaking the tweak factor iteratively. Also added test for regular runs of gudrun_dcs and runs of gudrun_dcs that iterate by tweaking the tweak factor. Closes #17.

Iterate by Tweak factor

---

src/gudrun_classes/beam.py
src/gudrun_classes/enums.py
src/gudrun_classes/gudrun_file.py
src/gudrun_classes/instrument.py
src/gudrun_classes/sample.py
tests/test_gudpy_io.py
tests/test_gudrun_classes.py

Exactly as described in #42. Closes #42.

Enumerate Instrument names.

---

.azure-pipelines/continuous.yml
.azure-pipelines/pr.yml
.azure-pipelines/release.yml
.azure-pipelines/templates/build.yml
.azure-pipelines/templates/create_release.yml
.azure-pipelines/templates/test.yml
ReleaseNotes.md
gudpy.spec

Added release pipeline.
Added version to gudpy.spec.

Release CI

---

src/gudrun_classes/gudrun_file.py
src/gudrun_classes/instrument.py
tests/test_gudpy_io.py

Simple PR - simply adds features as described in the title. Closes #55.

Added nxsDefinition attribute to Instrument, updated parsing and tests.

---

src/gudrun_classes/run_individual_files.py
src/gudrun_classes/tweak_factor_iterator.py
src/gudrun_classes/wavelength_subtraction_iterator.py

Created `RunIndividualFiles` class for running data files for each sample individually. The class is simple, and "inherits" (in some sense), some of the methods of `GudrunFile`, for modularity.
The class takes as input a `GudrunFile` object, and partitions it, so each data file for each `Sample` object, has it's own `Sample`.
For example:
```
g = GudrunFile("water.txt") # create GudrunFile object.
runIndividualFiles = RunIndividualFiles(g) # Partition it into individual data files.
runIndividualFiles.process() # Write out, purge, and call gudrun_dcs.
```
Also fixed some issues with docstrings in the iterator classes.
Closes #48.

Run files individually

---

src/gui/widgets/beam_widget.py
src/gui/widgets/container_widget.py
src/gui/widgets/gudpy_tables.py
src/gui/widgets/gudpy_tree.py
src/gui/widgets/instrument_widget.py
src/gui/widgets/main_window.py
src/gui/widgets/normalisation_widget.py
src/gui/widgets/sample_background_widget.py
src/gui/widgets/sample_widget.py
src/gui/widgets/ui_files/beamWidget.ui
src/gui/widgets/ui_files/containerWidget.ui
src/gui/widgets/ui_files/instrumentWidget.ui
src/gui/widgets/ui_files/mainWindow.ui
src/gui/widgets/ui_files/normalisationWidget.ui
src/gui/widgets/ui_files/sampleWidget.ui

Okay.. I think it is time for this monster PR to be opened again.
- Basic GUI structure
- GUI is functional.
- An input file can be loaded, altered, purged, viewed and run.
- UI files are being used for the core of the GUI design.
- Some custom widgets have been implemented e.g. `InstrumentWidget`, `BeamWidget`, etc.
- ModelView architecture is being implemented - and custom `QAbstractTableModels`, `QItemDelegates `and `QTableViews` have been implemented. These can be found in `src/gui/widgets/gudpy_tables.py`.
- Some bug fixes throughout the whole project.
Closes #40.

Prototype GUI

---

src/gudrun_classes/gudrun_file.py
src/gudrun_classes/sample.py
tests/test_gudpy_io.py
tests/test_gudrun_classes.py

Very simple PR that closes #82.

Run samples based on input file.

---

src/gui/widgets/instrument_widget.py

Handle changes in X-Scale through GUI

---

src/gui/widgets/iteration_dialog.py
src/gui/widgets/main_window.py
src/gui/widgets/ui_files/iterationDialog.ui

A minimal dialog to enable users to perform iterations has been implemented, currently this will act as a stub for implementing iterating in the future.

Minimal Iteration Dialog

---

src/gui/widgets/main_window.py
src/gui/widgets/purge_dialog.py

Simple PR to fix problems explained in #141, in regards to the `PurgeDialog`.

Fix purge dialog

---

.azure-pipelines/templates/build.yml
.azure-pipelines/templates/test.yml
tests/test_models.py

Tests have been implemented for the various models used throughout the GUI.
Closes #101.

Test models

---

src/gui/widgets/main_window.py

PR addressing the issue of tracking the progress of `purge_det` using the progress bar. This seems to be working, however could do with some testing to see how accurate/consistent it is.
Closes #131.

Track purge_det

---

src/gui/widgets/gudpy_tree.py
src/gui/widgets/slots/container_slots.py
src/gui/widgets/slots/normalisation_slots.py
src/gui/widgets/slots/sample_slots.py

This PR fixes up a couple of small issues I noticed with the GUI.
Closes #213 , #212.

Minor GUI fixes

---

src/gui/widgets/gudpy_charts.py

Small PR to plot the expected DCS level, closes #226.

Plot expected DCS level

---

src/gudrun_classes/gudrun_file.py

Write out bug

---

src/gui/widgets/gudpy_charts.py
src/gui/widgets/main_window.py

PR to update the plotting side of things.
- Implements plot translation, closes #239.
- Toggle plotting for each sample, closes #217.
- Implements further structure factor plotting options, closes #227.
- Toggle visibility of series' using legend, closes #230.

Plotting updates

---

src/gui/widgets/exponential_spinbox.py
src/gui/widgets/slots/beam_slots.py
src/gui/widgets/slots/container_slots.py
src/gui/widgets/slots/instrument_slots.py
src/gui/widgets/slots/normalisation_slots.py
src/gui/widgets/slots/sample_slots.py
src/gui/widgets/ui_files/mainWindow.ui

This PR fixes up the issues described in #250. Subsequently closes #250.
Edit: This PR is updated to also close #261 - it now prevents stepping below the minimum value of the exponential spin box, or above the maximum value of the exponential spin box. Also, updated to close #262.

Exponential spinbox units

---

src/gudrun_classes/gud_file.py
tests/test_gud_file.py

The `GudFile` parser has been refactored to parse in a similar fashion to the `GudrunFile` parser. Closes #254.

Refactor gud file parser

---

src/gui/widgets/main_window.py
src/gui/widgets/slots/normalisation_slots.py

Minor PR to fix the bug with progressing purges within release 2.0.

Fix purge progression bug

---

src/gudrun_classes/composition.py
src/gudrun_classes/gudrun_file.py

PR to implement saving of components to the input file. Also allows parsing of components on loading.

Store components

---

.azure-pipelines/templates/build.yml
ci/singularity/ubuntu20.04.def
src/gudrun_classes/instrument.py

This PR builds a .sif (Singularity Image File), which can be run using `singularity run`. This image uses Ubuntu 20.04, and aims to resolve dependancy problems with running GudPy across different versions of ubuntu, and flavours of linux. However, the final artifact has not yet been tested.
Closes #273.

Build Singularity image

---

src/gui/widgets/charts/chartview.py
src/gui/widgets/main_window.py

Small PR to fix a couple of bugs with plotting.
- Container plots being shown when no data exists.
- Combo boxes not being updated when focus of sample/container is changed.
- Errors occuring when chart.label() has not yet been initialised.

Minor charting fixes

---

src/gui/widgets/main_window.py
src/gui/widgets/slots/output_slots.py

PR to show output of multiple iterations in the "Output" tab. Closes #301.

Iteration Output

---

src/gui/widgets/dialogs/composition_dialog.py
src/gui/widgets/dialogs/composition_iteration_dialog.py
src/gui/widgets/slots/component_slots.py
src/gui/widgets/slots/container_slots.py
src/gui/widgets/slots/normalisation_slots.py
src/gui/widgets/slots/sample_slots.py
src/gui/widgets/tables/components_table.py
src/gui/widgets/tables/composition_table.py
src/gui/widgets/tables/ratio_composition_table.py

PR to fix various bugs with the Component / Composition models/tables. Closes #324.

Component / Composition bug fixes

---

src/gui/widgets/dialogs/iterate_composition_dialog.py

fix: issue with selecting components.

---

src/gudrun_classes/composition_iterator.py
tests/test_gudpy_workflows.py

Added tests for the following iterators:
- Thickness
- Composition
Closes #322.

Test iterators

---

ci/singularity/ubuntu20.04.def

Pip requirements were not being installed properly in the Singularity container, leading to the produced .sif not running.

fix: install pip requirements from requirements.txt.

---

gudpy/core/run_individual_files.py
gudpy/gui/widgets/core/main_window.py
gudpy/gui/widgets/ui_files/mainWindow.ui

PR implementing running files individually through the GUI.
Closes #337.

Run individual files (GUI)

---

gudpy/core/composition.py
gudpy/core/composition_iterator.py
gudpy/core/container.py
gudpy/core/data_files.py
gudpy/core/normalisation.py
gudpy/core/output_file_handler.py
gudpy/core/run_individual_files.py
gudpy/core/sample.py
gudpy/core/sample_background.py
gudpy/core/single_param_iterator.py
gudpy/core/tweak_factor_iterator.py
gudpy/core/wavelength_subtraction_iterator.py
gudpy/gui/widgets/charts/chart.py
gudpy/gui/widgets/charts/sample_plot_config.py
gudpy/gui/widgets/core/main_window.py
gudpy/gui/widgets/core/worker.py
gudpy/gui/widgets/dialogs/export_dialog.py
gudpy/gui/widgets/slots/component_slots.py
gudpy/gui/widgets/slots/container_slots.py
gudpy/gui/widgets/slots/normalisation_slots.py
gudpy/gui/widgets/slots/sample_background_slots.py
gudpy/gui/widgets/slots/sample_slots.py
gudpy/test/test_gudpy_workflows.py

Small PR fixing some minor bugs and making some code improvements to make interfacing with certain functionality less error prone and generally easier to do so.

General fixes and improvements

---

gudpy/core/file_library.py
gudpy/core/gudrun_file.py
gudpy/gui/widgets/core/main_window.py

This PR refactors the `CheckFilesExist` functionality to be more performant, and also ensures that this check is performed before any task is executed.

Check files before running

---

gudpy/core/config.py
gudpy/core/gudpy_yaml.py
gudpy/core/gudrun_file.py
gudpy/gui/widgets/core/gudpy_tree.py
gudpy/gui/widgets/core/main_window.py
gudpy/gui/widgets/dialogs/composition_acceptance_dialog.py
gudpy/gui/widgets/dialogs/iterate_composition_dialog.py
gudpy/gui/widgets/slots/sample_slots.py
gudpy/gui/widgets/tables/ratio_composition_table.py

PR fixing corruption of components when multiple GudrunFile objects are created. Closes #342.

Fix corrupted components

---

gudpy/gui/widgets/core/main_window.py
gudpy/gui/widgets/core/worker.py
gudpy/gui/widgets/dialogs/iterate_density_dialog.py
gudpy/gui/widgets/dialogs/iterate_inelasticity_subtractions_dialog.py
gudpy/gui/widgets/dialogs/iterate_radius_dialog.py
gudpy/gui/widgets/dialogs/iterate_thickness_dialog.py
gudpy/gui/widgets/dialogs/iterate_tweak_factor_dialog.py
gudpy/gui/widgets/dialogs/iteration_dialog.py

Fixes various iteration-related issues:
- Wavelength Subtraction Iterator was not performing as expected.
- Error handling during iterations.
- Prevent autosaving when iterating.
- Fix composition iterator - removed output organisation, which seemed to end up breaking the thread  somehow.
Closes #333, #343, #257.

Iteration fixes

---

ci/singularity/ubuntu20.04.def

This should fix the kernel issue with Qt6 on CentOS 7

Qt kernel fix

---

gudpy/core/file_library.py

Export fixes

---

gudpy/core/composition.py
gudpy/gui/widgets/dialogs/composition_dialog.py
gudpy/gui/widgets/slots/container_slots.py
gudpy/gui/widgets/slots/sample_slots.py
gudpy/gui/widgets/tables/composition_table.py
gudpy/gui/widgets/tables/ratio_composition_table.py

PR fixing issues described in #355. Subsequently closes #355.

Fix copy compositions

---

gudpy/gui/widgets/core/gudpy_tree.py

Very minor PR which ensures that selection/deselection of 'all' samples is applied in the context of *all* sample backgrounds, rather than just the focused one.

Select all samples

---

gudpy/gui/widgets/charts/chart.py
gudpy/gui/widgets/charts/sample_plot_config.py
gudpy/gui/widgets/charts/sample_plot_data.py

Somewhere along the line, logarithmic axes were disabled. This PR re-enables them.

Enable Logarithmic Axes

---

gudpy/core/gudrun_file.py
gudpy/core/run_batch_files.py
gudpy/gui/widgets/core/main_window.py
gudpy/gui/widgets/dialogs/batch_processing_dialog.py
gudpy/gui/widgets/ui_files/batchProcessingDialog.ui

Implements "propogation of first batch" during the batch processing pipeline.
Closes #372.

Continue iterations batch processing

---

gudpy/gui/widgets/dialogs/nexus_processing_dialog.py

Adds the missing NeXuS processing dialog.

Missing Nexus Dialog

---

gudpy/gui/widgets/ui_files/mainWindow.ui

Tiny PR changing ordering of the monitors in the GUI. Closes #381.

Change monitor ordering in GUI

---

gudpy/gui/widgets/charts/chart.py

PR making the visibility of samples persistent across plot modes, closes #385.

Sample Plot Visibilty

---

gudpy/gui/widgets/core/main_window.py

Small PR fixing issues with command completion not triggering within GudPy. Closes #380.

Command completion issues

---

gudpy/gui/widgets/slots/instrument_slots.py

Fix broken X-Scale (2)

---

gudpy/gui/widgets/core/main_window.py
gudpy/gui/widgets/dialogs/iteration_dialog.py

PR fixes issues outlined in #386, closes #386.

Fix inelasticity iterations

---

.github/workflows/continuous.yml
ci/settings.py
gudpy.spec

Quick PR to add a continuous CI workflow, giving us usable artifacts on every push to `main`.
It also moves the version of the main branch up to `0.4.0` in order to make it distinct from the current releases (`0.3.X`).

Continuous CI

---

.github/workflows/continuous.yml
.github/workflows/pr.yml
.github/workflows/publish/action.yml
.github/workflows/release.yml

This PR adds in some needed functionality and extra control to the publishing stage of the CI.

Publishing Control

---

.github/workflows/publish/action.yml

A quick PR to implement some changes to the logic used in the `if` expressions in the publishing action, after finding with JV2 that it didn't work as previously written!

Fix publishing logic

---

gudpy/core/enums.py
gudpy/core/nexus_processing.py
gudpy/gui/widgets/dialogs/nexus_processing_dialog.py
gudpy/gui/widgets/ui_files/nexusProcessingDialog.ui

GUI updates to allow interfacing to new functionality provided in ModEx.

Modex Interface
