disorderedmaterials/GudPy

src/gudrun_classes/gud_file.py
src/gudrun_classes/gudrun_file.py
tests/test_gud_file.py
tests/test_gudpy_io.py
tests/test_gudrun_classes.py

Instead of indexing lines as such: `instrument.name = firstword(lines[0])`, a stream based approach has been implemented.
The `GudrunFile` class now supports the following methods:
- `getNextToken`
- `peekNextToken`
- `consumeTokens`
- `consumeWhitespace`
- `consumeUpToDelim`
Which are used to maintain a stream within the `GudrunFile` (which is now stored in an attribute, `stream`).
So now, getting the instrument name may look as such: `instrument.name = self.getNextToken()`.
Clearly this is better practice, but also makes the code easier to read - and we no longer have to worry about applying offsets to the indexes after parsing attributes which are of dynamic lengths (`DataFiles`, `Composition`, `groupingParameterPanel` etc.).
This PR closes #70.

Stop indexing lines

---

src/gudrun_classes/config.py
src/gui/widgets/gudpy_tree.py

- The `GudPyTreeView` has been modified to use a `GudPyTreeModel`, which inherits `QAbstractItemModel`.
- The model does not rely on an external tree to maintain itself, rather it utilises the `index` and `parent` methods.
- No longer need `GudPyNode` class to describe nodes in the tree.
- Implementation is in line with the goal of the `ModelView` architecture.
Closes #84.

Manage GudPyTreeView using MV architecture solely

---

src/gui/widgets/instrument_widget.py
src/gui/widgets/ui_files/instrumentWidget.ui

Reorganised the general layout of the `InstrumentWidget`, and split up the fields into further categories (`config/monitors/binning/other`).
Took a more hierarchical approach to layouts - used horizontal layouts inside vertical layouts etc.
Aims to close #78 - however to main aim of this PR is to first ensure that we are on the right track following the feedback of #75.

Instrument Widget UI 

---

src/gui/widgets/gudpy_tree.py
src/gui/widgets/main_window.py

A context menu has been added so that when right clicking in the tree, a menu appears.
This menu offers the following functionality:
- Copy
- Cut
- Paste
- Insert
- Select All
- Deselect All
- Select only this sample
- Duplicate sample
- Duplicate sample without containers.
Each action is added in context, so depending on the context of the current index selected, different actions are offered.
Closes #89.

Tree context menu

---

src/gui/widgets/main_window.py

If no input file is loaded (i.e when the program initially starts), then the QStackedWidget and GudPyTreeView are hidden, and a range of actions (which require an input file) are disabled until one is loaded.
Closes #95.

Declutter interface / disable actions if no input file is loaded

---

src/gui/widgets/gudpy_tree.py

Very simple PR to force auto-selection of the `Instrument` in the `GudPyTreeView`, by default - to reflect the state of the `QStackedWidget` - which by default shows the `Instrument` tab. Closes #105.

Autoselect Instrument by default

---

src/gui/widgets/normalisation_widget.py
src/gui/widgets/ui_files/normalisationWidget.ui

Improved the aesthetics of the NormalisationWidget.
- Stopped setting size constraints on widgets.
- More incremental approach to layouts.
- Generally looks better.
- Haven't addressed the issue with using `QPushButtons` over `QToolButtons` for now, since I'd like to address this is it's own PR. (Possibly a PR alongside #90?)
Closes #80.

Normalisation widget

---

src/gudrun_classes/data_files.py
src/gudrun_classes/sample.py
src/gui/widgets/beam_widget.py
src/gui/widgets/container_widget.py
src/gui/widgets/instrument_widget.py
src/gui/widgets/sample_background_widget.py
src/gui/widgets/sample_widget.py

Fairly simple PR, fixing up some bugs identified in #108.
Main feature is that across `SampleBackgroundWidgets`, `SampleWidgets` and `ContainerWidgets`, slots are connected to the signals from the widgets in their own method, `setupUI()`, instead of being connected inside `initComponents()` - which caused multiple slots to be connected, where only one should have been.
Also fixed bugs with the `__str__` methods of `DataFiles` and `Sample`.
Closes #108, as mentioned above.

Fix browsing files

---

src/gui/widgets/instrument_widget.py

Small PR that closes #104. 
A `QRegExpValidator` has been implemented which leverages a regular expression, interfaced through a `QRegExp` - which only allows space delimited integers to be entered.

Regex for spectrum numbers.

---

src/gui/widgets/instrument_widget.py
src/gui/widgets/ui_files/instrumentWidget.ui

Implemented toggling the visibility of the grouping parameter panel within the `InstrumentWidget` - also resolved some layout problems with maximum size constraints on widgets.
One issue is present, that making the grouping parameter panel enlarges all of the group boxes, and then hiding the grouping parameter panel again does not revert these changes.

Toggle grouping parameter panel

---

src/gui/widgets/gudpy_tables.py
src/gui/widgets/sample_widget.py
src/gui/widgets/ui_files/instrumentWidget.ui
src/gui/widgets/ui_files/mainWindow.ui
src/gui/widgets/ui_files/sampleWidget.ui

The `SampleWidget` has been reorganised to utilise a `QTabWidget` to view the Sample's configuration, composition / geometry, Fourier transform parameters and advanced parameters.
Also modified the way that the **ancestor** widget is found (`GudPyMainWindow`).
Closes #114.

Tabify SampleWidget

---

src/gui/widgets/container_widget.py
src/gui/widgets/normalisation_widget.py
src/gui/widgets/sample_widget.py
src/gui/widgets/ui_files/containerWidget.ui
src/gui/widgets/ui_files/normalisationWidget.ui
src/gui/widgets/ui_files/sampleWidget.ui

Implemented handling choosing the FILE option for the Total Cross Section Source.
If the FILE option is selected, a hidden widget is made visible which allows browsing for a file, it gets hidden again if a different option is chosen in the combo box.
Closes #92.

Handle FILE for Total Cross Section Source

---

src/gudrun_classes/gudrun_file.py
src/gudrun_classes/purge_file.py
src/gui/widgets/dialogs/iteration_dialog.py
src/gui/widgets/main_window.py
src/gui/widgets/slots/beam_slots.py
tests/test_gudpy_io.py

PR to implement setting the working directory using `QProcess.setWorkingDirectory`. Closes #240.
Also fixed issue with cancelling the purge dialog producing a warning for the `purge_det` binary missing. Closes #242.

Set working dir

---

src/gudrun_classes/gudrun_file.py
src/gui/widgets/slots/beam_slots.py
src/gui/widgets/slots/instrument_slots.py
src/gui/widgets/ui_files/mainWindow.ui

This PR fixes up issues with absolute paths being used for configuration files within the `StartupFiles` sub-directory. Closes #248. Also, closes #247 - it turns out these handlers are there, but were not behaving as expected due to the above issue.

Use relative paths

---

src/gui/widgets/main_window.py

This PR attempts to fix the modification status functionality. Rather than setting the window title after a modification, we now use the `setWindowModified` method of the main window, to apply the modification status and have it persist in the title. Closes #265.

Modification status fix

---

bin/configs/NIMROD.txt
src/gudrun_classes/gudrun_file.py
src/gudrun_classes/instrument.py
src/gui/widgets/main_window.py
src/gui/widgets/ui_files/mainWindow.ui
tests/test_gudpy_io.py

This PR updates the way the results of `purge_det` are indicated. Now, a warning is produced, currently for `NIMROD` only, if the number of detectors that made it through the purge is below an acceptable threshold. Also, the number of good detectors is indicated on the `Instrument` page. This closes #263.

Purge with default parameters

---

src/gui/widgets/main_window.py

PR to apply the `.txt` suffix to the selected filename when using the `Save As..` option. This is to ensure that GudPy picks the file up when trying to load it in future. Closes #279.

Save with suffix

---

src/gui/widgets/charts/chart.py
src/gui/widgets/charts/chartview.py
src/gui/widgets/charts/enums.py
src/gui/widgets/charts/sample_plot_config.py
src/gui/widgets/main_window.py
src/gui/widgets/ui_files/mainWindow.ui

PR to fix up some charting issues and inconveniences.
- No longer plot mint01 and mdcs01 files together, with the expected DCS level on the summary page. Only do this for individual samples/containers. Closes #290.
- Fix bug with incorrect plot mode being shown after running gudrun_dcs - where the plot mode displayed doesn't match the combo box. Closes #295.
- Optionally split Structure Factor / RDF, rather than by default. Closes #292.
- Also, show co-ordinates in the chart of the mouse. Closes #293.

Chart updates #1

---

src/gudrun_classes/tweak_factor_iterator.py
src/gudrun_classes/wavelength_subtraction_iterator.py
src/gui/widgets/main_window.py

Minor PR to fix some iteration related problems.
- Sleep between iterations to try and ensure that files required to be read from are 'ready'. Closes #303.
- Use a deepcopy of the GudrunFile object to iterate on - to prevent intermediate changes whilst iterating to be applied to the reference GudrunFile object. Closes #304.

Iteration fixes

---

src/gudrun_classes/gudrun_file.py

PR to make matching using regex safe when parsing an input file. This solves a problem that occurs when one of the various configuration files are not present in the `StartupFiles` directory (hence, closes #314).

Safe Matching

---

src/gui/widgets/main_window.py

Small PR which fixes bug described in #320.
gudrun_dcs is automatically run after a purge is performed, when the purge was executed via a prompt (i.e. the prompt which suggests that detectors have not yet been purged).
Closes #320.

Run Gudrun after Purging

---

.azure-pipelines/templates/build.yml

Somehow the Singularity Compilation step of the Linux build pipeline has been broken. This PR fixes that.

Fix Singularity Compilation

---

gudpy/gui/widgets/slots/container_slots.py
gudpy/gui/widgets/slots/sample_slots.py
gudpy/gui/widgets/ui_files/mainWindow.ui

This PR potentially solves one of the original "issues" - #8. Whilst renaming the 'tweak factor' to 'packing fraction', and performing calculations during reading/writing etc. could be potentially dangerous, with newer/older input file formats, it doesn't do any harm to simply display the packing fraction. Hence, this PR implements an extra exponential spin box next to the Tweak Factor (for both samples and containers), this is updated as the tweak factor changes, and vice versa - however, the packing fraction is not stored as a class attribute.
This is just an idea - and certainly does not need to be merged in, if it's not an appropriate enhancement.
Closes #8.

Display Packing Fraction

---

gudpy/gui/widgets/core/main_window.py
gudpy/gui/widgets/slots/container_slots.py
gudpy/gui/widgets/slots/normalisation_slots.py
gudpy/gui/widgets/slots/sample_background_slots.py
gudpy/gui/widgets/slots/sample_slots.py
gudpy/gui/widgets/tables/data_file_list.py
gudpy/gui/widgets/ui_files/mainWindow.ui

This PR implements a explicit `QListView` for data files, which maintains a `QStringListModel`. This allows the list items to be mutable. Furthermore, a "duplicate" functionality has been implemented for data files.
Closes #356.

Mutable data files

---

gudpy/core/isotopes.py
gudpy/gui/widgets/tables/components_table.py
gudpy/gui/widgets/tables/composition_delegate.py
gudpy/gui/widgets/tables/composition_table.py
gudpy/test/test_models.py

This PR makes the composition tables throughout the GUI stricter.
- When a mass number is entered, the atomic symbol is used to determine if this is a valid isotope. If it is not, then the mass number is not applied.
- When an atomic symbol is entered, the mass number is used to determine if this is a valid isotope. If it is not, then the mass number is set to zero (natural).
The main purpose for this PR is that when invalid isotopes are entered, it breaks the expected DCS level calculations.
Doesn't really need testing or code review, just looking for conceptual feedback!

Strict Composition Table

---

gudpy/gui/widgets/core/main_window.py
gudpy/gui/widgets/dialogs/iterate_density_dialog.py
gudpy/gui/widgets/dialogs/iterate_inelasticity_subtractions_dialog.py
gudpy/gui/widgets/dialogs/iterate_radius_dialog.py
gudpy/gui/widgets/dialogs/iterate_thickness_dialog.py
gudpy/gui/widgets/dialogs/iterate_tweak_factor_dialog.py
gudpy/gui/widgets/dialogs/iteration_dialog.py

Small PR to fix a major bug with cancelling iteration dialogs freezing the GUI (i.e. controls not being unlocked as they should be).
Closes #363.

Cancel Iterations

---

gudpy/gui/widgets/ui_files/compositionAcceptanceDialog.ui
gudpy/gui/widgets/ui_files/compositionDialog.ui
gudpy/gui/widgets/ui_files/configsDialog.ui
gudpy/gui/widgets/ui_files/iterateCompositionDialog.ui
gudpy/gui/widgets/ui_files/iterateDensityDialog.ui
gudpy/gui/widgets/ui_files/iterateInelasticitySubtractionsDialog.ui
gudpy/gui/widgets/ui_files/iterateRadiusDialog.ui
gudpy/gui/widgets/ui_files/iterateThicknessDialog.ui
gudpy/gui/widgets/ui_files/iterateTweakFactorDialog.ui
gudpy/gui/widgets/ui_files/purgeDialog.ui
gudpy/gui/widgets/ui_files/viewInputDialog.ui

Small PR adding dialog titles to all dialogs used throughout GudPy - rather than the default window titles of `Dialog`.

Dialog titles

---

ci/singularity/ubuntu20.04.def
gudpy/gui/widgets/core/main_window.py
gudpy/gui/widgets/slots/instrument_slots.py

The "Nexus Processing" button had no slot connected to its "triggered" signal. This has been fixed, and now also gets enabled/disabled with change of data file type.

Nexus Dialog Fix

---

gudpy/gui/widgets/charts/chartview.py

Series were not being toggled on marker clicks, this PR fixes this by ensuring that mouse click/release events cascade down the widget hierarchy, i.e. from the GudPyChartView to the GudPyChart. Closes #375.

Fix legend marker click events

---

gudpy/gui/widgets/core/main_window.py

Another fix, for another bug... When running NeXuS processing, GudPy was crashing due to an issue with incrementing the progress bar.

Fix NeXuS processing progression.

---

gudpy.spec

PR should fix issues with windows build

fix: use platform specific path separators. JS reimplimented

---

.github/workflows/continuous.yml

This PR fixes a few things with the `continuous` pipeline:
- Code version was not set in the pipeline so artifacts were not correctly renamed for publication
- A publishing step did not exist, so no artifacts were pushed to Harbor
Of course, there's no way of testing this until it gets merged back in to `main`!

Continuous CI++

---

.github/workflows/pr.yml
.github/workflows/test/action.yml
.github/workflows/testresults/action.yml

A PR to fix a clash when publishing test results.  This would occasionally fail if, coincidentally, more than one runner from a different OS tried to publish its results simultaneously.
As recommended by the author of the action to publish test results, this is now done in bulk by a single task.

Separate Test Publishing

---

.github/workflows/get-externals/action.yml
.github/workflows/publish/action.yml
gudpy.spec

This PR bumps the version of the continuous (development) release to `0.5.0` in order to distinguish it from the current release (`0.4.0`).
It also fixes (again) the publishing action which didn't update the continuous build correctly due to some missing flags.

Update Continuous Release Version
